schema_version = "1.0.0"
id = "Batch_ActorX_Import_Addon"
version = "0.0.1"
name = "Batch ActorX (psk, pskx, psa) Import addon for Blender"
tagline = "Import multiple ActorX models, meshes, textures and animations at a time."
maintainer = "RhyCynn"
type = "add-on"
website = "https://github.com/RhyCynn/batch_actorx_import_addon"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
blender_version_max = "4.9.9"
license = ["SPDX:MIT"]
wheels = [
    "./wheels/ruamel.yaml-0.18.10-py3-none-any.whl",
    "./wheels/magicattr-0.1.6-py2.py3-none-any.whl",
]
